inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 49
    n_positions: 101

training:
    data: matrix_completion
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 10000
    keep_every_steps: 100000
    train_steps: 100000
    curriculum:
        dims:
            start: 49
            end: 49
            inc: 1
            interval: 2000
