inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 25
    n_positions: 101

training:
    data: matrix_completion
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 10000
    keep_every_steps: 100000
    train_steps: 50001
    curriculum:
        dims:
            start: 25
            end: 25
            inc: 1
            interval: 2000
